[Feature] slack changelog payload multiline test 2

diff --git a/.github/workflows/client-builder.yaml b/.github/workflows/client-builder.yaml
--- a/.github/workflows/client-builder.yaml
+++ b/.github/workflows/client-builder.yaml
@@ -347,11 +347,10 @@ jobs:
         run: |
           if [ -f "${{ env.LAST_BUILD_COMMIT_FILE }}" ]; then
             last_build_commit=$(cat ${{ env.LAST_BUILD_COMMIT_FILE }})
-            changelog_commits="$((set -o pipefail; git log --oneline --no-merges ${last_build_commit}..HEAD | tr '"' "'" | while read LINE; do echo -n ${LINE}\\n; done) || echo "Unable to generate changelog from the commit ${last_build_commit}")"
-            echo "changelog_commits=${changelog_commits}" >> $GITHUB_OUTPUT
-            echo "${changelog_commits}"
+            CHANGELOG_COMMITS="$((set -o pipefail; git log --oneline --no-merges ${last_build_commit}..HEAD | tr '"' "'" | while read LINE; do echo -n ${LINE}\\n; done) || echo "Unable to generate changelog from the commit ${last_build_commit}")"
+            echo "changelog_commits=${CHANGELOG_COMMITS}" >> $GITHUB_OUTPUT
 
-            if [ -z "$(echo "${changelog_commits}" | tr -d "[:blank:]")" ]; then
+            if [ -z "$(echo "${CHANGELOG_COMMITS}" | tr -d "[:blank:]")" ]; then
               echo "changelog=false" >> $GITHUB_OUTPUT
             else
               echo "changelog=true" >> $GITHUB_OUTPUT
@@ -368,6 +367,7 @@ jobs:
           payload: |
             {
               "thread_ts": "${{ steps.slackToken.outputs.thread_ts }}",
+              "text": "Content cannot be rendered",
               "attachments": [
                 {
                   "color": "grey",
