slack changelog try to get rid payload file

diff --git a/.github/workflows/client-builder.yaml b/.github/workflows/client-builder.yaml
--- a/.github/workflows/client-builder.yaml
+++ b/.github/workflows/client-builder.yaml
@@ -347,16 +347,13 @@ jobs:
         run: |
           if [ -f "${{ env.LAST_BUILD_COMMIT_FILE }}" ]; then
             last_build_commit=$(cat ${{ env.LAST_BUILD_COMMIT_FILE }})
-            changelog=$((set -o pipefail; git log --oneline --no-merges $last_build_commit..HEAD | tr '"' "'") || echo "Unable to generate changelog from the commit ${last_build_commit}")
+            echo "changelog_commits=$((set -o pipefail; git log --oneline --no-merges $last_build_commit..HEAD | tr '"' "'") || echo "Unable to generate changelog from the commit ${last_build_commit}")" >> $GITHUB_OUTPUT
 
             if [ -z "$(echo "${changelog}" | tr -d "[:blank:]")" ]; then
               echo "changelog=false" >> $GITHUB_OUTPUT
             else
               echo "changelog=true" >> $GITHUB_OUTPUT
             fi
-
-            printf "{\"thread_ts\": \"${{ steps.slackToken.outputs.thread_ts }}\",\"attachments\": [{\"color\": \"grey\",\"fields\": [{\"value\": \"%s\"}]}]}" "${changelog//$'\n'/\\n}" >../slack.msg
-
           fi
 
       - name: Post message to Slack - Add changelog to thread
@@ -366,7 +363,20 @@ jobs:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
         with:
           channel-id: ${{ inputs.slack_channel_id }}
-          payload-file-path: slack.msg
+          payload: |
+            {
+              "thread_ts": "${{ steps.slackToken.outputs.thread_ts }}",
+              "attachments": [
+                {
+                  "color": "grey",
+                  "fields": [
+                    {
+                      "value": "${{ steps.changelog.outputs.changelog_commits }}"
+                    }
+                  ]
+                }
+              ]
+            }
 
       - name: Build
         working-directory: ${{ env.APP_DIR }}
