[Feature] slack changelog payload multiline

diff --git a/.github/workflows/client-builder.yaml b/.github/workflows/client-builder.yaml
--- a/.github/workflows/client-builder.yaml
+++ b/.github/workflows/client-builder.yaml
@@ -347,7 +347,7 @@ jobs:
         run: |
           if [ -f "${{ env.LAST_BUILD_COMMIT_FILE }}" ]; then
             last_build_commit=$(cat ${{ env.LAST_BUILD_COMMIT_FILE }})
-            echo "changelog_commits=$((set -o pipefail; git log --oneline --no-merges $last_build_commit..HEAD | tr '"' "'") || echo "Unable to generate changelog from the commit ${last_build_commit}")" >> $GITHUB_OUTPUT
+            echo "changelog_commits=$((set -o pipefail; git log --oneline --no-merges ${last_build_commit}..HEAD | tr '"' "'" | while read LINE; do echo -n ${LINE}\\n; done) || echo "Unable to generate changelog from the commit ${last_build_commit}")" >> $GITHUB_OUTPUT
 
             if [ -z "$(echo "${changelog}" | tr -d "[:blank:]")" ]; then
               echo "changelog=false" >> $GITHUB_OUTPUT
@@ -371,6 +371,7 @@ jobs:
                   "color": "grey",
                   "fields": [
                     {
+                      "type": "mrkdwn",
                       "value": "${{ steps.changelog.outputs.changelog_commits }}"
                     }
                   ]
